#!/bin/bash

PORTA=8888

# ORIGINAL(deve ser adicionado --allow-root depois de --no-browser para realmente funcionar;
# acontece erro por docker usar usuário root e não roda o servidor jo jupyter)
# docker run -i -t -p 8888:8888 continuumio/miniconda3 /bin/bash -c "/opt/conda/bin/conda install jupyter -y --quiet && mkdir /opt/notebooks && /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser"

instala_jupyter(){
    if [ "$(conda list | grep jupyter)" == "" ]; then
        /opt/conda/bin/conda install jupyter -y &&  mkdir /opt/notebooks
    fi
}

docker run -i -t -p $PORTA:8888 continuumio/miniconda3 /bin/bash -c "/opt/conda/bin/conda install jupyter -y &&  mkdir /opt/notebooks && echo -e '\n\nUtilize o endereço/link informado  abaixo para acessar o Jupyter Notebook\nCTRL+c para PARAR\n\n' && /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser --allow-root"
