version: '3.1'

services:

  mysql-8-4:
    image: mysql:8.4
    container_name: mysql-8-4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: masterkey
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
