version: '3.1'

services:

  mysql57:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: masterkey
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql

